stages:
  - build

variables:
  CARGO_HOME: "${CI_PROJECT_DIR}/.cargo"
  RUST_BACKTRACE: 1

cache:
  paths:
    - .cargo/
    - target/

rust-latest:
  stage: build
  image: rust:latest
  script:
    - apt update
    - apt install libgtk-3-dev --no-install-recommends -y
    - cargo test
    - cargo build --release
    - mv target/release/lyriek ./
  artifacts:
    name: lyriek
    paths:
      - lyriek
