name: Rust

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: update repositories
        run: sudo apt update

      - name: install dependencies
        run: sudo apt install libgtk-3-dev --no-install-recommends -y

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
